version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1

  customerdb:
     image: mongo

  customers:
    image: ${DOCKER_REGISTRY-}customers
    build:
      context: .
      dockerfile: Customers/Dockerfile
  
 
  cart:
    image: ${DOCKER_REGISTRY-}cart
    build:
      context: .
      dockerfile: Cart/Dockerfile

volumes:
  mongo_disk:
  elastic_disc:
    driver: local
